# Generated by Django 5.1.3 on 2024-11-24 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0006_alter_note_created_alter_note_updated"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={"ordering": ["-updated"]},
        ),
    ]
