# Generated by Django 2.2.16 on 2021-05-28 07:28

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="what_is",
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name="story",
            name="what_should_be",
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
