# Generated by Django 2.2.16 on 2021-06-02 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0002_auto_20210528_0928"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="story",
            options={
                "ordering": ["created"],
                "verbose_name": "Story",
                "verbose_name_plural": "Stories",
            },
        ),
    ]
