# Generated by Django 2.2.16 on 2021-06-02 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_auto_20210602_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-created'], 'verbose_name': 'Story', 'verbose_name_plural': 'Stories'},
        ),
    ]
