# Generated by Django 2.2.16 on 2021-07-30 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['date'], 'verbose_name': 'Achievement', 'verbose_name_plural': 'Achievements'},
        ),
    ]
