# Generated by Django 2.2.16 on 2021-07-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0002_auto_20210730_1627"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievement",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
