# Generated by Django 2.2.4 on 2020-09-08 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('is_done', models.BooleanField(default=False)),
                ('has_failed', models.BooleanField(default=False)),
                ('activate', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_dos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('is_archived', 'deadline', 'is_done', 'has_failed', 'activate', 'name'),
            },
        ),
        migrations.CreateModel(
            name='NormalToDo',
            fields=[
                ('todo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todos.ToDo')),
            ],
            bases=('todos.todo',),
        ),
        migrations.CreateModel(
            name='RepetitiveToDo',
            fields=[
                ('todo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todos.ToDo')),
                ('duration', models.DurationField()),
                ('repetitions', models.PositiveSmallIntegerField(default=None, null=True)),
                ('previous', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='todos.RepetitiveToDo')),
            ],
            bases=('todos.todo',),
        ),
        migrations.CreateModel(
            name='PipelineToDo',
            fields=[
                ('todo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todos.ToDo')),
                ('previous', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_to_dos', to='todos.ToDo')),
            ],
            bases=('todos.todo',),
        ),
        migrations.CreateModel(
            name='NeverEndingToDo',
            fields=[
                ('todo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todos.ToDo')),
                ('duration', models.DurationField()),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='todos.NeverEndingToDo')),
            ],
            bases=('todos.todo',),
        ),
    ]
