# Generated by Django 2.2.4 on 2020-09-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='ACTIVE', max_length=20),
        ),
    ]
