# Generated by Django 2.2.16 on 2020-10-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_auto_20201021_1857"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repetitivetodo",
            name="repetitions",
            field=models.PositiveSmallIntegerField(default=None),
            preserve_default=False,
        ),
    ]
