# Generated by Django 2.2.16 on 2021-02-22 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20201021_1928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('deadline', 'status', 'activate', 'name')},
        ),
        migrations.RemoveField(
            model_name='todo',
            name='is_archived',
        ),
    ]
