# Generated by Django 2.2.4 on 2020-09-13 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_todo_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('is_archived', 'deadline', 'status', 'activate', 'name')},
        ),
        migrations.RemoveField(
            model_name='todo',
            name='has_failed',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='is_done',
        ),
    ]
