# Generated by Django 2.2.16 on 2020-10-01 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_auto_20200913_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='neverendingtodo',
            name='previous2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next2', to='todos.NeverEndingToDo'),
        ),
    ]
