# Generated by Django 2.2.16 on 2021-02-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0004_auto_20210222_1421"),
    ]

    operations = [
        migrations.AddField(
            model_name="repetitivetodo",
            name="blocked",
            field=models.BooleanField(default=False),
        ),
    ]
