# Generated by Django 2.2.16 on 2020-10-01 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_neverendingtodo_previous2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neverendingtodo',
            name='previous',
        ),
    ]
