# Generated by Django 2.2.16 on 2021-04-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0005_repetitivetodo_blocked"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="created",
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AddField(
            model_name="todo",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
