# Generated by Django 2.2.16 on 2020-10-01 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_auto_20201001_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neverendingtodo',
            old_name='previous2',
            new_name='previous',
        ),
    ]
