# Generated by Django 2.2.16 on 2020-10-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0010_auto_20201001_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='neverendingtodo',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
