# Generated by Django 2.2.4 on 2019-11-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='goal_view_goal_choice',
            field=models.CharField(choices=[('ALL', 'Show all goals.'), ('ACTIVE', 'Show all goals that are considered active.'), ('STAR', 'Show all starred goals.'), ('UNREACHED', 'Show all not yet achieved goals.'), ('ACHIEVED', 'Show all achieved goals.'), ('DEPTH', 'Show all goals within the depth range.'), ('ARCHIVE', 'Show all goals that are in the archive.'), ('NONE', 'Show no goals.')], default='ALL', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='goal_choice',
            field=models.CharField(choices=[('ALL', 'Show all goals.'), ('ACTIVE', 'Show all goals that are considered active.'), ('STAR', 'Show all starred goals.'), ('UNREACHED', 'Show all not yet achieved goals.'), ('ACHIEVED', 'Show all achieved goals.'), ('DEPTH', 'Show all goals within the depth range.'), ('ARCHIVE', 'Show all goals that are in the archive.'), ('NONE', 'Show no goals.')], default='ALL', max_length=10),
        ),
    ]
