# Generated by Django 2.2.16 on 2020-10-21 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='treeview_neverendingtodos_choice',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='treeview_normaltodos_choice',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='treeview_pipelinetodos_choice',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='treeview_repetitivetodos_choice',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='treeview_todos_delta',
        ),
    ]
