# Generated by Django 2.2.4 on 2019-11-06 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191106_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='treeview_goal_choice',
            field=models.CharField(choices=[('ALL', 'Show all goals.'), ('ACTIVE', 'Show all goals that are considered active.'), ('STAR', 'Show all starred goals.'), ('UNREACHED', 'Show all not yet achieved goals.'), ('ACHIEVED', 'Show all achieved goals.'), ('DEPTH', 'Show all goals within the depth range.'), ('ARCHIVE', 'Show all goals that are in the archive.'), ('NONE', 'Show no goals.')], default='ALL', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='treeview_goal_depth',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='treeview_link_choice',
            field=models.CharField(choices=[('ALL', 'Show all links.'), ('RELATED', 'Show master or sub goal related links.'), ('XRELATED', 'Show master and sub goal related links.'), ('NONE', 'Show no links.')], default='ALL', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='treeview_multipletodos_choice',
            field=models.CharField(choices=[('ALL', "Show all to do's."), ('ACTIVE', "Show all active to do's"), ('UNFINISHED', "Show all unfinished to do's"), ('DELTA', 'Show all to dos that are active and with a deadline within the delta range.'), ('OVERDUE', 'Show all to dos that are overdue.'), ('ORANGE', 'Show all to dos that are active or orange or red.'), ('RELATED', 'Show goal related to dos.'), ('NONE', "Show no to do's.")], default='ALL', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='treeview_neverendingtodos_choice',
            field=models.CharField(choices=[('ALL', "Show all to do's."), ('ACTIVE', "Show all active to do's"), ('UNFINISHED', "Show all unfinished to do's"), ('DELTA', 'Show all to dos that are active and with a deadline within the delta range.'), ('OVERDUE', 'Show all to dos that are overdue.'), ('ORANGE', 'Show all to dos that are active or orange or red.'), ('RELATED', 'Show goal related to dos.'), ('NONE', "Show no to do's.")], default='ALL', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='treeview_normaltodos_choice',
            field=models.CharField(choices=[('ALL', "Show all to do's."), ('ACTIVE', "Show all active to do's"), ('UNFINISHED', "Show all unfinished to do's"), ('DELTA', 'Show all to dos that are active and with a deadline within the delta range.'), ('OVERDUE', 'Show all to dos that are overdue.'), ('ORANGE', 'Show all to dos that are active or orange or red.'), ('RELATED', 'Show goal related to dos.'), ('NONE', "Show no to do's.")], default='ALL', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='treeview_pipelinetodos_choice',
            field=models.CharField(choices=[('ALL', "Show all to do's."), ('ACTIVE', "Show all active to do's"), ('UNFINISHED', "Show all unfinished to do's"), ('DELTA', 'Show all to dos that are active and with a deadline within the delta range.'), ('OVERDUE', 'Show all to dos that are overdue.'), ('ORANGE', 'Show all to dos that are active or orange or red.'), ('RELATED', 'Show goal related to dos.'), ('NONE', "Show no to do's.")], default='ALL', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='treeview_progressmonitor_choice',
            field=models.CharField(choices=[('ALL', 'Show all progress monitors.'), ('UNREACHED', 'Show all not yet fully loaded progress monitors.'), ('LOADED', 'Show all fully loaded progress monitors.'), ('RELATED', 'Show goal related progress monitors.'), ('NONE', 'Show no progress monitors.')], default='ALL', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='treeview_repetitivetodos_choice',
            field=models.CharField(choices=[('ALL', "Show all to do's."), ('ACTIVE', "Show all active to do's"), ('UNFINISHED', "Show all unfinished to do's"), ('DELTA', 'Show all to dos that are active and with a deadline within the delta range.'), ('OVERDUE', 'Show all to dos that are overdue.'), ('ORANGE', 'Show all to dos that are active or orange or red.'), ('RELATED', 'Show goal related to dos.'), ('NONE', "Show no to do's.")], default='ALL', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='treeview_strategy_choice',
            field=models.CharField(choices=[('ALL', 'Show all strategies.'), ('STAR', 'Show all starred strategies.'), ('RELATED', 'Show goal related strategies.'), ('NONE', 'Show no strategies.')], default='ALL', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='treeview_todos_delta',
            field=models.DurationField(blank=True, default=datetime.timedelta(days=7)),
        ),
    ]
