# Generated by Django 2.2.4 on 2019-11-06 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191106_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='treeview_link_choice',
        ),
    ]
