# Generated by Django 2.2.4 on 2019-11-06 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_treeview_link_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='treeview_progressmonitor_choice',
            new_name='treeview_monitor_choice',
        ),
    ]
