# Generated by Django 2.2.4 on 2020-02-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200206_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='progress_monitor_choice',
            field=models.CharField(choices=[('ALL', 'Show all progress monitors.'), ('UNREACHED', 'Show all not yet fully loaded progress monitors.'), ('LOADED', 'Show all fully loaded progress monitors.'), ('NONE', 'Show no progress monitors.')], default='ALL', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='treeview_monitor_choice',
            field=models.CharField(choices=[('ALL', 'Show all progress monitors.'), ('UNREACHED', 'Show all not yet fully loaded progress monitors.'), ('LOADED', 'Show all fully loaded progress monitors.'), ('NONE', 'Show no progress monitors.')], default='ALL', max_length=10),
        ),
    ]
