# Generated by Django 2.2.4 on 2020-04-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200206_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='show_archived_objects',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='link_choice',
            field=models.CharField(choices=[('ALL', 'Show all links.'), ('NONE', 'Show no links.')], default='ALL', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='never_ending_to_dos_choice',
            field=models.CharField(choices=[('ALL', "Show all to do's."), ('ACTIVE', "Show all active to do's"), ('UNFINISHED', "Show all unfinished to do's"), ('DELTA', 'Show all to dos that are active and with a deadline within the delta range.'), ('OVERDUE', 'Show all to dos that are overdue.'), ('ORANGE', 'Show all to dos that are active or orange or red.'), ('NONE', "Show no to do's.")], default='ALL', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='normal_to_dos_choice',
            field=models.CharField(choices=[('ALL', "Show all to do's."), ('ACTIVE', "Show all active to do's"), ('UNFINISHED', "Show all unfinished to do's"), ('DELTA', 'Show all to dos that are active and with a deadline within the delta range.'), ('OVERDUE', 'Show all to dos that are overdue.'), ('ORANGE', 'Show all to dos that are active or orange or red.'), ('NONE', "Show no to do's.")], default='ALL', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pipeline_to_dos_choice',
            field=models.CharField(choices=[('ALL', "Show all to do's."), ('ACTIVE', "Show all active to do's"), ('UNFINISHED', "Show all unfinished to do's"), ('DELTA', 'Show all to dos that are active and with a deadline within the delta range.'), ('OVERDUE', 'Show all to dos that are overdue.'), ('ORANGE', 'Show all to dos that are active or orange or red.'), ('NONE', "Show no to do's.")], default='ALL', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='repetitive_to_dos_choice',
            field=models.CharField(choices=[('ALL', "Show all to do's."), ('ACTIVE', "Show all active to do's"), ('UNFINISHED', "Show all unfinished to do's"), ('DELTA', 'Show all to dos that are active and with a deadline within the delta range.'), ('OVERDUE', 'Show all to dos that are overdue.'), ('ORANGE', 'Show all to dos that are active or orange or red.'), ('NONE', "Show no to do's.")], default='ALL', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='starview_neverendingtodos_choice',
            field=models.CharField(choices=[('ALL', "Show all to do's."), ('ACTIVE', "Show all active to do's"), ('UNFINISHED', "Show all unfinished to do's"), ('DELTA', 'Show all to dos that are active and with a deadline within the delta range.'), ('OVERDUE', 'Show all to dos that are overdue.'), ('ORANGE', 'Show all to dos that are active or orange or red.'), ('NONE', "Show no to do's.")], default='ALL', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='starview_normaltodos_choice',
            field=models.CharField(choices=[('ALL', "Show all to do's."), ('ACTIVE', "Show all active to do's"), ('UNFINISHED', "Show all unfinished to do's"), ('DELTA', 'Show all to dos that are active and with a deadline within the delta range.'), ('OVERDUE', 'Show all to dos that are overdue.'), ('ORANGE', 'Show all to dos that are active or orange or red.'), ('NONE', "Show no to do's.")], default='ALL', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='starview_pipelinetodos_choice',
            field=models.CharField(choices=[('ALL', "Show all to do's."), ('ACTIVE', "Show all active to do's"), ('UNFINISHED', "Show all unfinished to do's"), ('DELTA', 'Show all to dos that are active and with a deadline within the delta range.'), ('OVERDUE', 'Show all to dos that are overdue.'), ('ORANGE', 'Show all to dos that are active or orange or red.'), ('NONE', "Show no to do's.")], default='ALL', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='starview_repetitivetodos_choice',
            field=models.CharField(choices=[('ALL', "Show all to do's."), ('ACTIVE', "Show all active to do's"), ('UNFINISHED', "Show all unfinished to do's"), ('DELTA', 'Show all to dos that are active and with a deadline within the delta range.'), ('OVERDUE', 'Show all to dos that are overdue.'), ('ORANGE', 'Show all to dos that are active or orange or red.'), ('NONE', "Show no to do's.")], default='ALL', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='treeview_neverendingtodos_choice',
            field=models.CharField(choices=[('ALL', "Show all to do's."), ('ACTIVE', "Show all active to do's"), ('UNFINISHED', "Show all unfinished to do's"), ('DELTA', 'Show all to dos that are active and with a deadline within the delta range.'), ('OVERDUE', 'Show all to dos that are overdue.'), ('ORANGE', 'Show all to dos that are active or orange or red.'), ('NONE', "Show no to do's.")], default='ALL', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='treeview_normaltodos_choice',
            field=models.CharField(choices=[('ALL', "Show all to do's."), ('ACTIVE', "Show all active to do's"), ('UNFINISHED', "Show all unfinished to do's"), ('DELTA', 'Show all to dos that are active and with a deadline within the delta range.'), ('OVERDUE', 'Show all to dos that are overdue.'), ('ORANGE', 'Show all to dos that are active or orange or red.'), ('NONE', "Show no to do's.")], default='ALL', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='treeview_pipelinetodos_choice',
            field=models.CharField(choices=[('ALL', "Show all to do's."), ('ACTIVE', "Show all active to do's"), ('UNFINISHED', "Show all unfinished to do's"), ('DELTA', 'Show all to dos that are active and with a deadline within the delta range.'), ('OVERDUE', 'Show all to dos that are overdue.'), ('ORANGE', 'Show all to dos that are active or orange or red.'), ('NONE', "Show no to do's.")], default='ALL', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='treeview_repetitivetodos_choice',
            field=models.CharField(choices=[('ALL', "Show all to do's."), ('ACTIVE', "Show all active to do's"), ('UNFINISHED', "Show all unfinished to do's"), ('DELTA', 'Show all to dos that are active and with a deadline within the delta range.'), ('OVERDUE', 'Show all to dos that are overdue.'), ('ORANGE', 'Show all to dos that are active or orange or red.'), ('NONE', "Show no to do's.")], default='ALL', max_length=10),
        ),
    ]
