# Generated by Django 5.1.3 on 2024-11-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_customuser_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="new_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Neue E-Mail"
            ),
        ),
    ]
