# Generated by Django 2.2.4 on 2020-08-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200406_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='strategy_main_choice',
            field=models.CharField(choices=[('ALL', 'Show all strategies.'), ('ACTIVE', 'Show all strategies considered active.'), ('STAR', 'Show all starred strategies.'), ('NONE', 'Show no strategies.')], default='ALL', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='strategy_choice',
            field=models.CharField(choices=[('ALL', 'Show all strategies.'), ('ACTIVE', 'Show all strategies considered active.'), ('STAR', 'Show all starred strategies.'), ('NONE', 'Show no strategies.')], default='ALL', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='treeview_strategy_choice',
            field=models.CharField(choices=[('ALL', 'Show all strategies.'), ('ACTIVE', 'Show all strategies considered active.'), ('STAR', 'Show all starred strategies.'), ('NONE', 'Show no strategies.')], default='ALL', max_length=10),
        ),
    ]
