# Generated by Django 2.2.4 on 2020-08-13 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200813_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='goal_choice',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='goal_depth',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='link_choice',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='progress_monitor_choice',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='starview_neverendingtodos_choice',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='starview_normaltodos_choice',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='starview_pipelinetodos_choice',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='starview_repetitivetodos_choice',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='starview_todos_delta',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='strategy_choice',
        ),
    ]
