# Generated by Django 2.2.4 on 2019-08-07 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('why', models.TextField(blank=True, null=True)),
                ('impact', models.TextField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('progress', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('is_starred', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('progress', 'deadline', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('weight', models.SmallIntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('rolling', models.DurationField(blank=True, null=True)),
                ('progress', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('is_starred', models.BooleanField(default=False)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='goals.Goal')),
            ],
            options={
                'ordering': ('progress', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('is_done', models.BooleanField(default=False)),
                ('has_failed', models.BooleanField(default=False)),
                ('activate', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_dos', to='goals.Strategy')),
            ],
            options={
                'ordering': ('is_done', 'has_failed', 'deadline', 'activate', 'name'),
            },
        ),
        migrations.CreateModel(
            name='MultipleToDo',
            fields=[
                ('todo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='goals.ToDo')),
            ],
            bases=('goals.todo',),
        ),
        migrations.CreateModel(
            name='ProgressMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor', models.CharField(max_length=300)),
                ('weight', models.PositiveSmallIntegerField(default=1)),
                ('steps', models.PositiveSmallIntegerField()),
                ('step', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('progress', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_monitors', to='goals.Goal')),
            ],
            options={
                'ordering': ('progress', 'goal'),
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.SmallIntegerField(default=1)),
                ('proportion', models.SmallIntegerField(default=100)),
                ('progress', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('master_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_links', to='goals.Goal')),
                ('sub_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_links', to='goals.Goal')),
            ],
            options={
                'ordering': ('progress', 'master_goal'),
            },
        ),
        migrations.AddField(
            model_name='goal',
            name='sub_goals',
            field=models.ManyToManyField(related_name='master_goals', through='goals.Link', to='goals.Goal'),
        ),
        migrations.AddField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RepetitiveToDo',
            fields=[
                ('todo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='goals.ToDo')),
                ('end_day', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('previous', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='goals.RepetitiveToDo')),
            ],
            bases=('goals.todo',),
        ),
        migrations.CreateModel(
            name='PipelineToDo',
            fields=[
                ('todo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='goals.ToDo')),
                ('previous', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_to_dos', to='goals.ToDo')),
            ],
            bases=('goals.todo',),
        ),
        migrations.CreateModel(
            name='NeverEndingToDo',
            fields=[
                ('todo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='goals.ToDo')),
                ('duration', models.DurationField()),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='goals.NeverEndingToDo')),
            ],
            bases=('goals.todo',),
        ),
    ]
