# Generated by Django 2.2.16 on 2020-10-21 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('why', models.TextField(blank=True, null=True)),
                ('impact', models.TextField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('addition', models.TextField(blank=True, null=True)),
                ('progress', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('is_starred', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('is_archived', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_starred', models.BooleanField(default=False)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='goals.Goal')),
            ],
            options={
                'ordering': ('is_archived', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ProgressMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('weight', models.PositiveSmallIntegerField(default=1)),
                ('steps', models.PositiveSmallIntegerField()),
                ('step', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_archived', models.BooleanField(default=False)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_monitors', to='goals.Goal')),
            ],
            options={
                'ordering': ('is_archived', 'name', 'goal'),
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField(default=1)),
                ('is_archived', models.BooleanField(default=False)),
                ('master_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_links', to='goals.Goal')),
                ('sub_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_links', to='goals.Goal')),
            ],
            options={
                'ordering': ('is_archived', 'master_goal'),
            },
        ),
        migrations.AddField(
            model_name='goal',
            name='sub_goals',
            field=models.ManyToManyField(related_name='master_goals', through='goals.Link', to='goals.Goal'),
        ),
    ]
