# Generated by Django 2.2.4 on 2019-08-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repetitivetodo',
            name='trash',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
