# Generated by Django 2.2.4 on 2019-11-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_repetitivetodo_trash'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goal',
            name='archived_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
