# Generated by Django 2.2.16 on 2020-10-21 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='sub_goal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master_links', to='goals.Goal'),
        ),
    ]
