# Generated by Django 2.2.4 on 2019-11-06 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_auto_20191104_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='archived',
            new_name='is_archived',
        ),
    ]
