# Generated by Django 2.2.4 on 2019-11-06 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_auto_20191106_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='archived_text',
            new_name='addition',
        ),
    ]
