# Generated by Django 2.2.4 on 2019-11-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_auto_20191106_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progressmonitor',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='strategy',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
