# Generated by Django 2.2.4 on 2019-11-07 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_auto_20191107_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalToDo',
            fields=[
                ('todo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='goals.ToDo')),
            ],
            bases=('goals.todo',),
        ),
    ]
