# Generated by Django 2.2.4 on 2019-11-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_normaltodo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ('is_archived', 'progress', 'deadline', 'name')},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ('is_archived', 'progress', 'master_goal')},
        ),
        migrations.AlterModelOptions(
            name='progressmonitor',
            options={'ordering': ('is_archived', 'progress', 'goal')},
        ),
        migrations.AlterModelOptions(
            name='strategy',
            options={'ordering': ('is_archived', 'progress', 'name')},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('is_archived', 'deadline', 'is_done', 'has_failed', 'activate', 'name')},
        ),
        migrations.AlterField(
            model_name='repetitivetodo',
            name='trash',
            field=models.BooleanField(default=False),
        ),
    ]
