# Generated by Django 2.2.4 on 2019-11-10 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0009_repetitivetodo_repetitions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repetitivetodo',
            name='end_day',
        ),
        migrations.RemoveField(
            model_name='repetitivetodo',
            name='trash',
        ),
    ]
