# Generated by Django 2.2.4 on 2019-11-10 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0010_auto_20191110_2106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultipleToDo',
        ),
    ]
