# Generated by Django 2.2.4 on 2020-09-15 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0011_delete_multipletodo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='strategy',
        ),
        migrations.RemoveField(
            model_name='normaltodo',
            name='todo_ptr',
        ),
        migrations.RemoveField(
            model_name='pipelinetodo',
            name='previous',
        ),
        migrations.RemoveField(
            model_name='pipelinetodo',
            name='todo_ptr',
        ),
        migrations.RemoveField(
            model_name='repetitivetodo',
            name='previous',
        ),
        migrations.RemoveField(
            model_name='repetitivetodo',
            name='todo_ptr',
        ),
        migrations.DeleteModel(
            name='NeverEndingToDo',
        ),
        migrations.DeleteModel(
            name='NormalToDo',
        ),
        migrations.DeleteModel(
            name='PipelineToDo',
        ),
        migrations.DeleteModel(
            name='RepetitiveToDo',
        ),
        migrations.DeleteModel(
            name='ToDo',
        ),
    ]
