# Generated by Django 2.2.16 on 2020-10-12 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0012_auto_20200915_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ('is_archived', 'master_goal')},
        ),
        migrations.AlterModelOptions(
            name='progressmonitor',
            options={'ordering': ('is_archived', 'monitor', 'goal')},
        ),
        migrations.AlterModelOptions(
            name='strategy',
            options={'ordering': ('is_archived', 'name')},
        ),
        migrations.RemoveField(
            model_name='link',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='link',
            name='proportion',
        ),
        migrations.RemoveField(
            model_name='progressmonitor',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='rolling',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='weight',
        ),
    ]
