# Generated by Django 2.2.16 on 2020-10-12 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0013_auto_20201012_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ('is_archived', 'name')},
        ),
        migrations.RemoveField(
            model_name='goal',
            name='progress',
        ),
    ]
