# Generated by Django 2.2.16 on 2020-10-13 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0016_auto_20201013_2246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progressmonitor',
            options={'ordering': ('is_archived', 'name', 'goal')},
        ),
        migrations.RenameField(
            model_name='progressmonitor',
            old_name='monitor',
            new_name='name',
        ),
    ]
